#!/usr/bin/perl

use LWP::Simple;

$file = '/home/tree/projects/mangaprobe/mangalist';

if (! -r $file) {
    print "Argh can't read $file!\n";
    exit;
}

open (file, $file);

while (<file>) {
    chomp;
    $manga = $_;
    if ($manga) {
        %info = get_info($manga);

        print_info(\%info);
        print "\n";
    }
}

close (file);

sub get_info {
    $url = $_[0];

    my(%info);

    if ($url =~ m/mangable/) {
        $site = LWP::Simple::get $url;
        %info = get_mangable_info($url, $site);
    }
    elsif ($url =~ m/mangastream/) {
        if (!$mangastream) {
            $mangastream = LWP::Simple::get "http://mangastream.com/manga";
        }
        %info = get_mangastream_info($url, $mangastream);
    }
    elsif ($url =~ m/mangareader/) {
        $site = LWP::Simple::get $url;
        %info = get_mangareader_info($url, $site);
    }
    elsif ($url =~ m/mangafox/) {
        $site = LWP::Simple::get $url;
        %info = get_mangafox_info($url, $site);
    }

    $info{"url"} = $url;

    if (!$info{"time"}) {
        $info{"time"} = "000000";
    }
    if (!$info{"datetime"}) {
        $info{"datetime"} = $info{"date"} . $info{"time"};
    }

    return %info;
}

sub get_mangable_info {
    $url = $_[0];
    my(%manga);

    $manga{"site"} = $site = $_[1];
    $manga{"domain"} = "mangable";

    if( $site =~ m/<title>(.*?) Manga<\/title>/ ) {
        $manga{"manga"} = $1;
    }

    if( $site =~ m/
            <div\s*id="title">.*?<\/div>
            .*?
            <ul\s*id="list_entry_chapter">
                (.*?)
            <\/ul>
        /xs
    ) {
        $chapters = $1;
        $manga{"chapters"} = $chapters;
    }

    if( $chapters =~ m/<a href="(http:\/\/.*?)" title=".*?(\d*)\s*">/ ) {
        $manga{"link"} = $1;
        $manga{"chapter"} = $2;
    }
    # Sep 4, 2010
    if( $chapters =~ m/<span>(.{3}) (\d{2}), (\d{4})<\/span>/ ) {
        if (length ($2) == 1) {
            $d = "0$2";
        }
        else {
            $d = $2;
        }
        $m = get_month_num($1);
        $manga{"date"} = "$3$m$d";
    }

    return %manga;
}

sub get_mangastream_info {
    $url = $_[0];
    my(%manga);

    $manga{"site"} = $site = $_[1];
    $manga{"domain"} = "mangastream";

    if ($url =~ m/:([^:]*?)$/) {
        $manga{"manga"} = $1;
    }

    if ($site =~ m/
            <th\s*style="width:80%">
                .*?
                $manga{"manga"}
                .*?
            <\/th>
            (.*?)
            <th\s*style="width:80%">
        /xsi
    ) {
        $chapters = $manga{"chapters"} = $1;
    }

    if ($chapters =~ m/<a\s*href="(.*?)">(\d*)\s*-\s*(.*?)<\/a>/) {
        $manga{"link"} = "http://mangastream.com$1";
        $manga{"chapter"} = $2;
        $manga{"title"} = $3;
    }
    # Sep 2nd, 2010
    if ($chapters =~ m/<em>(.*?)\s(\d+).*?(\d{4})<\/em>/) {
        if (length ($2) == 1) {
            $d = "0$2";
        }
        else {
            $d = $2;
        }
        $m = get_month_num($1);
        $manga{"date"} = "$3$m$d";
    }

    return %manga;
}

sub get_mangareader_info {
    $url = $_[0];
    my(%manga);

    $manga{"site"} = $site = $_[1];
    $manga{"domain"} = "mangareader";

    if ($site =~ m/<title>(.*?)\sManga\s-.*?<\/title>/) {
        $manga{"manga"} = $1;
    }

    if ($site =~ m/
            ([^<]*?
            <\/a>
                [^<]*?<\/td>\s*
            <td><a\shref="javascript:void\(0\);"><\/a><\/td>\s*
            <td\sclass="no">
                [\s\d-:]*
            <\/td>)
            \s*<\/tr>\s*<\/tbody>
            /xs
    ) {
        $latest = $manga{"chapters"} = $1;
    }

    if ($latest =~ m/href="(.*?)"/) {
        $manga{"link"} = "http://www.mangareader.net/$1";
    }

    if ($latest =~ m/
            href=".*?">
                \s*(.*?)\sChapter   #1 match manga name
                \s*(\d*)            #2 match chapter num
                [^:]*:
                \s*(.*?)            #3 match chapter title
            <\/td>/xs
    ) {
        $manga{"chapter"} = $2;
        $manga{"title"} = $3;
    }

    if ($latest =~ m/
            <td\sclass="no">
                \s*
                (\d*)-(\d*)-(\d*)   #DD-MM-YYYY
                \s(\d*):(\d*):(\d*) #HH:MM:SS
                \s*
            <\/td>
        /xs
    ) {
        if (length ($1) == 1) {
            $d = "0$1";
        }
        else {
            $d = $1;
        }
        $m = $2;
        $manga{"date"} = "$3$2$d";
        $manga{"time"} = "$4$5$6";
    }

    return %manga;
}

sub get_mangafox_info {
    $url = $_[0];
    my(%manga);

    $manga{"site"} = $site = $_[1];
    $manga{"domain"} = "mangafox";

    if ($site =~ m/<title>Manga\sFox:\s(.*?)\sManga\sSeries<\/title>/) {
        $manga{"manga"} = $1;
    }

    if ($site =~ m/
            <tr>\s*
                <td>\s*<a\shref="[^"]*"[^>]*>edit<\/a>\s*
                .*?
            \s*<\/tr>
        /xs
    ) {
        $latest = $manga{"chapters"} = $&;
    }

    if ($latest =~ m/
            <a\shref="(\/manga.*)"\sclass="chico">  #1: link
                \s*.*?Vol\.\d*\s*
                Ch\.(\d*):                          #2: chapter
                \s(.*?)                             #3: title
                \s*<\/a>
        /xs
    ) {
        $manga{"link"} = "http://www.mangafox.com$1";
        $manga{"chapter"} = $2;
        $manga{"title"} = $3;
    }

    if ($latest =~ m/<td class="no">(.*?)<\/td>/) {
        if ($1 =~ m/Today/) {
            $manga{"date"} = get_todays_date();
        }
        elsif ($1 =~ m/Yesterday/) {
            $manga{"date"} = get_yesterdays_date();
        }
        else {
            $manga{"date"} = $1;
        }
    }

    return %manga;
}

sub get_month_num {
    %months = (
        Jan => "01",
        Feb => "02",
        Mar => "03",
        Apr => "04",
        May => "05",
        Jun => "06",
        Jul => "07",
        Aug => "08",
        Sep => "09",
        Okt => "10",
        Nov => "11",
        Dec => "12",
    );
    return $months{$_[0]};
}

sub get_date {
    ($s,$min,$h,$d,$m,$y) = localtime($_[0]);
    $y += 1900;
    if (length($m) == 1) { $m = "0$m"; }
    if (length($d) == 1) { $d = "0$d"; }
    return "$y$m$d";
}

sub get_todays_date {
    return get_date(time());
}

sub get_yesterdays_date {
    return get_date(time() - 24 * 60 * 60);
}

sub print_info {
    #print "site: $_[0]{site}\n";
    #print "chapters: $_[0]{chapters}\n";

    print "url:     $_[0]{url}\n";
    print "manga:   $_[0]{manga}\n";
    print "domain:  $_[0]{domain}\n";
    print "link:    $_[0]{link}\n";
    print "chapter: $_[0]{chapter}\n";
    print "title:   $_[0]{title}\n";
    print "date:    $_[0]{date}\n";
    print "datetime:$_[0]{datetime}\n";
    print "time:    $_[0]{time}\n";
}

